Feature/change password
Lekky71/tickie-main-service pull request #13
Opened 2023-04-23 13:34 UTC by myke-awoniran

finished Change Password Endpoint for an Already loggedIn user
Complete Endpoint Yaml specification

2023-04-29 11:21 UTC, Lekky71 requested changes
Good work just some changes to be made.

2023-04-29 11:21 UTC, Lekky71 commented on spec/api.yaml
> +          type: string
No validation. Kindly add, you can refer to the SignUpRequest.

2023-04-29 11:21 UTC, Lekky71 commented on src/controlllers/user.controller.ts
> +export async function handleManagePassword(req: IExpressRequest, res: ExpressResponse): Promise<void> {
`handleChangePassword` ?

2023-04-29 11:21 UTC, Lekky71 commented on src/controlllers/user.controller.ts
> +    ResponseManager.success(res, response)
End statements with semicolon. ;

2023-04-29 11:21 UTC, Lekky71 commented on src/services/user.service.ts
> +  if (!userAuth.verifyPassword(props.currentPassword))
Always put braces around IF statements.

2023-04-29 11:25 UTC, myke-awoniran commented on src/controlllers/user.controller.ts
> +export async function handleManagePassword(req: IExpressRequest, res: ExpressResponse): Promise<void> {
yes

2023-05-02 19:22 UTC, Lekky71 approved these changes

2023-05-02 19:22 UTC, merged